name = "docs-theme"
license = "Apache 2.0"
licenselink = "https://github.com/goombaio/docs-theme/blob/develop/LICENSE"
description = "Default themne for Gommba project documentation site."
homepage = "http://goombaproject.io"
tags = ["documentation", "minimal", "simple", "clean"]
features = ["minimal", "responsive", "simple", "clean", "light"]
min_version = "0.30"

[author]
  name = "Raül Pérez"
  homepage = "http://repejota.com"
